import { useLocation } from 'react-router-dom'
import '../styles/resources.css'

export function ResourceNav() {
  return <nav className="resource-links" aria-label="Recursos Express Solution"><a href="/impostos-brasileiros-boston">Brasileiros em Boston</a><a href="/en/boston-tax-guide" lang="en">English resources</a><a href="/sobre">Sobre Kelly Moraes</a></nav>
}
function Layout({ children, english = false }) {
  return <div className="resources-page"><header><a href="/" aria-label="Express Solution: início"><img src="/image/express-solution-logo.svg" width="220" height="80" alt="Express Solution" /></a><ResourceNav /></header><main>{children}</main><footer><p>Express Solution Tax &amp; Accounting, Inc.</p><a href="mailto:support@express-solution.com">support@express-solution.com</a><p>{english ? 'Educational information. Individual tax and legal decisions require an assessment of your circumstances.' : 'Conteúdo educacional. Decisões fiscais e jurídicas individuais dependem da análise da sua situação.'}</p><a href="/">{english ? 'Explore the Portuguese tax guide' : 'Conhecer o Guia de Impostos'}</a></footer></div>
}
export function About() {
  return <Layout><p className="resource-kicker">Sobre os materiais</p><h1>Kelly Moraes e os guias Express Solution</h1><p className="resource-lead">Informação em português para compreender melhor os impostos e a abertura de empresa nos Estados Unidos.</p><section className="resource-author"><img src="/image/autora.png" width="230" height="280" alt="Kelly Moraes, autora dos guias Express Solution" loading="lazy" /><div><h2>Uma biblioteca para organizar suas próximas decisões</h2><p>Kelly Moraes é a autora do Guia Completo de Impostos para Imigrantes nos EUA e de Abertura de Empresa nos EUA, apresentados pela Express Solution Tax &amp; Accounting, Inc.</p><p>Os materiais reúnem explicações, checklists e pontos de atenção. O objetivo é ajudar o leitor a preparar documentos e perguntas antes de tomar decisões ou buscar atendimento individual.</p></div></section><section><h2>Fontes e limites do conteúdo</h2><p>Nas páginas de orientação, priorizamos links do IRS e dos órgãos públicos de Massachusetts. Regras, formulários e prazos podem mudar; consulte a fonte oficial referente ao seu ano fiscal. Exemplos educacionais não representam promessa de economia ou reembolso.</p><h2>Contato e correções</h2><p>Para dúvidas sobre os materiais ou para apontar uma informação que precisa de revisão, escreva para <a href="mailto:support@express-solution.com">support@express-solution.com</a>. Inclua o título do guia e a página ou o link a que se refere.</p></section></Layout>
}
export function BostonResources() {
  const english = useLocation().pathname.startsWith('/en/')
  return <Layout english={english}>{english ? <English /> : <Portuguese />}</Layout>
}
function Sources({ english = false }) {
  return <section><h2>{english ? 'Official sources to keep at hand' : 'Fontes oficiais para consultar'}</h2><ul>
    <li><a href="https://www.irs.gov/individuals/international-taxpayers/foreign-persons">IRS: Foreign persons</a> — {english ? 'Federal tax information for foreign individuals.' : 'Informações fiscais federais para pessoas estrangeiras.'}</li>
    <li><a href="https://www.mass.gov/personal-income-tax">Massachusetts Department of Revenue: Personal Income Tax</a> — {english ? 'State income tax resources.' : 'Orientações sobre imposto de renda estadual.'}</li>
    <li><a href="https://www.mass.gov/guides/personal-income-tax-for-part-year-residents">Massachusetts: Part-Year Residents</a> — {english ? 'Information for people who moved during the tax year.' : 'Informações para quem se mudou durante o ano fiscal.'}</li>
  </ul><p>{english ? 'Sources consulted on September 13, 2026. Check the current official guidance for your tax year.' : 'Fontes consultadas em 13 de setembro de 2026. Confira a orientação oficial vigente para o seu ano fiscal.'}</p></section>
}
function Portuguese() {
  return <><p className="resource-kicker">Boston · Massachusetts · Em português</p><h1>Impostos para brasileiros em Boston: por onde começar?</h1><p className="resource-lead">Comece separando três assuntos: suas obrigações federais, as regras de Massachusetts e a organização dos documentos. Os guias Express Solution ajudam a preparar essa conversa em português.</p><nav className="resource-toc" aria-label="Nesta página"><a href="#federal-estadual">Federal e estadual</a><a href="#documentos">O que organizar</a><a href="#perguntas">Perguntas frequentes</a><a href="#guias">Conheça os guias</a></nav>
  <section id="federal-estadual"><h2>Morar em Boston exige olhar para duas esferas</h2><p>O IRS administra os impostos federais. Em Massachusetts, o Department of Revenue é a referência para o imposto de renda estadual. Entregar uma declaração federal não significa, por si só, ter resolvido suas obrigações estaduais.</p><p>Para quem vive na Grande Boston, mudou de estado ou chegou aos EUA durante o ano, as datas da mudança e os locais de trabalho são informações importantes. A análise de residência fiscal federal também não deve ser confundida automaticamente com a situação migratória.</p><p>Veja as orientações do <a href="https://www.irs.gov/individuals/international-taxpayers/foreign-persons">IRS para pessoas estrangeiras</a> e do <a href="https://www.mass.gov/personal-income-tax">Massachusetts Department of Revenue</a>.</p></section>
  <section id="documentos"><h2>Um roteiro para preparar seus documentos</h2><p>Use esta lista como ponto de partida para uma conversa. Os documentos necessários dependem da sua situação.</p><ol><li><strong>Registre as mudanças:</strong> anote quando chegou aos EUA, onde morou e em quais estados trabalhou.</li><li><strong>Separe os comprovantes recebidos:</strong> mantenha informes como W-2 e 1099, quando houver, junto dos demais registros de renda.</li><li><strong>Organize o trabalho por conta própria:</strong> reúna receitas, despesas e comprovantes; não trate toda despesa como dedutível sem análise.</li><li><strong>Leve as dúvidas por escrito:</strong> dependentes, documentos faltantes, rendas de outros países e mudanças de atividade merecem atenção individual.</li></ol><aside className="resource-note"><h3>Exemplo de organização</h3><p>Se você se mudou para Boston no meio do ano, crie uma linha do tempo com as datas e os endereços anteriores. Separe os comprovantes por período. Isso ajuda o profissional a avaliar a sua situação; não determina sozinho quais declarações serão necessárias.</p></aside></section>
  <section id="perguntas"><h2>Perguntas frequentes</h2><h3>Quem mora em Massachusetts precisa declarar imposto estadual?</h3><p>A obrigação depende da situação de residência, renda e das regras do ano fiscal. Consulte as orientações do estado ou peça uma análise individual; não presuma que a resposta será igual para todos.</p><h3>O guia serve para quem mora na Grande Boston?</h3><p>O Guia de Impostos apresenta conceitos e organização fiscal nos EUA, em português. Esta página complementa a leitura com referências de Massachusetts. O livro não substitui a análise das regras estaduais aplicáveis ao seu caso.</p><h3>Quero abrir uma empresa em Boston. Qual guia devo conhecer?</h3><p>A apostila Abertura de Empresa nos EUA ajuda a organizar perguntas sobre estrutura, proprietários, estado de operação e responsabilidades fiscais. As exigências concretas de registro e licenciamento devem ser confirmadas com os órgãos competentes.</p><h3>Como falar com a Express Solution em português?</h3><p>Envie sua dúvida para <a href="mailto:support@express-solution.com">support@express-solution.com</a>. Informe se o assunto é um material digital ou uma dúvida sobre atendimento.</p></section><Guides /><Sources /></>
}
function English() {
  return <><p className="resource-kicker">Boston · Massachusetts · Portuguese-language resources</p><h1>Boston tax resources for Brazilian and Portuguese-speaking readers</h1><p className="resource-lead">Start by separating federal taxes, Massachusetts requirements and your personal records. Express Solution presents Portuguese-language guides by Kelly Moraes to help readers prepare better questions.</p><p><a href="/impostos-brasileiros-boston" lang="pt-BR">Leia esta orientação em português</a></p><section><h2>Federal and state taxes are separate questions</h2><p>The IRS is the federal tax authority. The Massachusetts Department of Revenue provides state income tax guidance. Completing a federal return does not, by itself, resolve state filing obligations.</p><p>If you moved to Greater Boston during the year, keep a timeline of where you lived and worked. Federal tax residency should not automatically be equated with immigration status. Check the <a href="https://www.irs.gov/individuals/international-taxpayers/foreign-persons">IRS guidance for foreign persons</a> for the relevant framework.</p></section><section><h2>Prepare for a conversation in Portuguese</h2><ol><li>Record arrival dates, moves and the states where you worked.</li><li>Gather income documents, including W-2 and 1099 forms when applicable, and other income records.</li><li>Keep self-employment receipts and records organized. A business expense is not automatically deductible.</li><li>Write down questions about dependents, missing documents, foreign income and changes in your work.</li></ol><aside className="resource-note"><h3>A practical example</h3><p>Someone who moved to Boston midyear can organize records by period and keep the dates and previous addresses together. This helps a professional assess the situation; it does not determine the required returns on its own.</p></aside></section><section><h2>Common questions</h2><h3>Does everyone in Massachusetts need to file a state return?</h3><p>Filing obligations depend on residence, income and the applicable tax-year rules. Refer to official guidance and seek an individual assessment.</p><h3>Are the books in English?</h3><p>No. Both guides are written in Portuguese. This page helps English-language searches reach resources intended for Portuguese-speaking readers.</p><h3>Which guide covers starting a business?</h3><p>Abertura de Empresa nos EUA introduces questions about structure, ownership, operating state and fiscal responsibilities. Confirm specific registration and licensing requirements with the relevant authorities.</p><h3>How can I contact Express Solution?</h3><p>Email <a href="mailto:support@express-solution.com">support@express-solution.com</a> with your question about a guide or an inquiry about assistance.</p></section><Guides english /><Sources english /></>
}
function Guides({ english = false }) {
  return <section id="guias"><h2>{english ? 'Explore the guides in Portuguese' : 'Escolha a leitura para o seu próximo passo'}</h2><div className="resource-guides"><a href="/"><img src="/image/tax-guide-cover.png" width="447" height="558" loading="lazy" alt="Guia Completo de Impostos para Imigrantes nos EUA" /><h3>Guia de Impostos</h3><p>{english ? 'Documents, income and tax organization.' : 'Documentos, rendas e organização fiscal.'}</p></a><a href="/abertura-de-empresa-nos-eua"><img src="/image/business-opening-cover.png" width="447" height="558" loading="lazy" alt="Abertura de Empresa nos EUA" /><h3>Abertura de Empresa nos EUA</h3><p>{english ? 'Structure, planning and responsibilities.' : 'Estrutura, planejamento e responsabilidades.'}</p></a></div><p>{english ? 'Meet the author: ' : 'Conheça a autora: '}<a href="/sobre">Kelly Moraes</a>.</p></section>
}
export function NotFound() { return <Layout><h1>Página não encontrada</h1><p>O endereço pode ter mudado. <a href="/">Volte para conhecer os guias Express Solution.</a></p></Layout> }
